/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab6_douglasrivera;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author famii
 */
public class VentaDeAgregar extends javax.swing.JFrame {

    /**
     * Creates new form VentaDeAgregar
     */
    public VentaDeAgregar() {
        initComponents();
    }
private String Genero = "";
private String Tipo = "";
private int Puntuacion = -1;
    public static ArrayList <TipoProgramas> Programas = new ArrayList();
    private TipoProgramas tipoPrograma;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void actualizarPrograma(int indice){
        this.tipoPrograma = Programas.get(indice);
        this.jtxtNombrePrograma.setText(tipoPrograma.getNombre());
        this.jtxtAño.setText(tipoPrograma.getYearLanzamiento()+"");
        this.jSpinner1.setValue(tipoPrograma.getPuntos());
        this.jcbGeneroPrograma.setSelectedItem(tipoPrograma.getGenero());
        this.jcbTipoPrograma.setSelectedItem(tipoPrograma.getTipo());
        
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtxtNombrePrograma = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jcbGeneroPrograma = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jcbTipoPrograma = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jtxtAño = new javax.swing.JTextField();
        jBAgregarPrograma = new javax.swing.JButton();
        jBAgregarPrograma1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 36)); // NOI18N
        jLabel1.setText("Nombre:");

        jtxtNombrePrograma.setFont(new java.awt.Font("Tempus Sans ITC", 0, 36)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 0, 36)); // NOI18N
        jLabel2.setText("Genero:");

        jcbGeneroPrograma.setFont(new java.awt.Font("Tempus Sans ITC", 0, 36)); // NOI18N
        jcbGeneroPrograma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Comedia", "Romance", "Terror", "SyFy", "Suspenso", "Accion" }));
        jcbGeneroPrograma.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbGeneroProgramaItemStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 0, 36)); // NOI18N
        jLabel3.setText("Tipo:");

        jcbTipoPrograma.setFont(new java.awt.Font("Tempus Sans ITC", 0, 36)); // NOI18N
        jcbTipoPrograma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Anime", "Serie", "Documental", "Pelicula" }));
        jcbTipoPrograma.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbTipoProgramaItemStateChanged(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 0, 36)); // NOI18N
        jLabel4.setText("Puntuacion:");

        jSpinner1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 36)); // NOI18N
        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(5, 1, 10, 1));
        jSpinner1.setMaximumSize(new java.awt.Dimension(1, 10));
        jSpinner1.setMinimumSize(new java.awt.Dimension(1, 1));
        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 0, 36)); // NOI18N
        jLabel5.setText("Año de Lanzamiento:");

        jtxtAño.setFont(new java.awt.Font("Tempus Sans ITC", 0, 36)); // NOI18N

        jBAgregarPrograma.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jBAgregarPrograma.setText("Agregar Programa");
        jBAgregarPrograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarProgramaActionPerformed(evt);
            }
        });

        jBAgregarPrograma1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jBAgregarPrograma1.setText("Regresar");
        jBAgregarPrograma1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarPrograma1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jBAgregarPrograma1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtxtAño, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(36, 36, 36)
                                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jtxtNombrePrograma)
                                        .addComponent(jcbTipoPrograma, 0, 179, Short.MAX_VALUE))
                                    .addComponent(jcbGeneroPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(353, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jBAgregarPrograma)
                .addGap(308, 308, 308))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBAgregarPrograma1)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtNombrePrograma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jcbGeneroPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jcbTipoPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtxtAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(jBAgregarPrograma)
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
        if (evt.getSource() == jSpinner1) {
            int seleccionado =(Integer)jSpinner1.getValue();
            this.Puntuacion = seleccionado;
        }
    }//GEN-LAST:event_jSpinner1StateChanged

    private void jBAgregarProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarProgramaActionPerformed
        this.Tipo =  (String) jcbTipoPrograma.getSelectedItem();
        this.Genero =  (String) jcbGeneroPrograma.getSelectedItem();
        this.Puntuacion =  (Integer) jSpinner1.getValue();
        boolean valido = true;
        if (this.jtxtNombrePrograma.getText() == null || "".equals(this.jtxtNombrePrograma.getText())) {
            JOptionPane.showConfirmDialog(this, "Ingrese el nombre");
            valido = false;       
        }
        if (this.jtxtAño.getText() == null || "".equals(this.jtxtAño.getText())) {
            JOptionPane.showConfirmDialog(this, "Ingrese el año");
            valido = false;       
        }
        if (this.Genero == null || "".equals(this.Genero)) {
            JOptionPane.showConfirmDialog(this, "Ingrese el genero del programa");
            valido = false;
        }
        if (this.Tipo == null || "".equals(this.Tipo)) {
            JOptionPane.showConfirmDialog(this, "Ingrese el tipo de programa");
            valido = false;       
        }
        if (this.Puntuacion == -1 || "".equals(this.Puntuacion)) {
            JOptionPane.showConfirmDialog(this, "Ingrese la puntuacion");
            valido = false;       
        }
        if (valido && this.tipoPrograma==null) {
            // int Puntos, int YearLanzamiento, String Nombre, String Tipo, String Genero
            TipoProgramas estu = new TipoProgramas(Puntuacion, Integer.parseInt(jtxtAño.getText()), jtxtNombrePrograma.getText(), this.Tipo, this.Genero);
            Programas.add(estu);
           /* DefaultListModel modelo
                    = (DefaultListModel) jlistE.getModel();

            modelo.addElement(estu);
            this.jlistE.setModel(modelo);
*/
        } else {
             tipoPrograma.setGenero(this.Genero);
              tipoPrograma.setNombre(this.jtxtNombrePrograma.getText());
               tipoPrograma.setPuntos(this.Puntuacion);
                tipoPrograma.setYearLanzamiento(Integer.parseInt(jtxtAño.getText()));
                tipoPrograma.setTipo(this.Tipo);
                
        }
    }//GEN-LAST:event_jBAgregarProgramaActionPerformed

    private void jcbGeneroProgramaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbGeneroProgramaItemStateChanged
        if (evt.getSource() == jcbGeneroPrograma) {
            String seleccionado = (String) jcbGeneroPrograma.getSelectedItem();
            this.Genero = seleccionado;
        }
    }//GEN-LAST:event_jcbGeneroProgramaItemStateChanged

    private void jcbTipoProgramaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbTipoProgramaItemStateChanged
        if (evt.getSource() == jcbTipoPrograma) {
            String seleccionado = (String) jcbTipoPrograma.getSelectedItem();
            this.Tipo = seleccionado;
        }
    }//GEN-LAST:event_jcbTipoProgramaItemStateChanged

    private void jBAgregarPrograma1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarPrograma1ActionPerformed
        this.setVisible(false);
        this.tipoPrograma = null;
        Menu menu = new Menu();
        menu.setVisible(true);
    }//GEN-LAST:event_jBAgregarPrograma1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentaDeAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentaDeAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentaDeAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentaDeAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentaDeAgregar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAgregarPrograma;
    private javax.swing.JButton jBAgregarPrograma1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JComboBox<String> jcbGeneroPrograma;
    private javax.swing.JComboBox<String> jcbTipoPrograma;
    private javax.swing.JTextField jtxtAño;
    private javax.swing.JTextField jtxtNombrePrograma;
    // End of variables declaration//GEN-END:variables
}
